config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :movies, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director

  include PgSearch::Model

  multisearchable against: [:title, :synopsis]

  pg_search_scope :search_by_title_and_synopsis,
                  against: [:title, :synopsis],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }

  pg_search_scope :global_search,
                  against: [:title, :synopsis],
                  associated_against: {
                    director: [:first_name, :last_name]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  include PgSearch::Model

  multisearchable against: [:title, :synopsis]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:query].present?
      # postgresql full-text search:
      # query = <<-SQL
      # title @@ :search_term
      # OR synopsis @@ :search_term
      # OR directors.first_name @@ :search_term
      # OR directors.last_name @@ :search_term
      # SQL
      # @movies = Movie.joins(:director).where(query, search_term: "%#{params[:query]}%")

      @movies = Movie.global_search(params[:query])
    else
      @movies = Movie.all
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImdbSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <h1 class="text-center">Movies (and TV Shows...)</h1>

      <%= form_tag movies_path, method: :get, class: 'd-flex' do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a movie"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>

      <div id="movies">
        <% @movies.each do |movie| %>
          <h4><%= movie.title %></h4>
          <p><%= movie.synopsis %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>